= Neo4j Movies Example Application - Asp.net WebApi Version

=== Requirements
* Have Neo4j running with the Movies Dataset (http://neo4j.com/download[Download & Install])
* Visual Studio 2013

WARNING: You will need the *Microsoft .NET Framework 4.5.2 Developer Pack* (http://www.microsoft.com/en-us/download/details.aspx?id=42637[Download & Install]) if you are running Visual Studio 2013, this is to allow transactions to utilize the `async` part of Neo4jClient. Users with _Visual Studio 2015_ do _not_ need the install.

=== Stack
* Neo4jClient https://github.com/Readify/Neo4jClient
* Asp.net WebApi

=== Run locally
* Start your local Neo4j Server (http://neo4j.com/download[Download & Install]), open the http://localhost:7474[Neo4j Browser]. Then install the Movies data-set with `:play movies`, click the statement, and hit the triangular "Run" button
* Open up the solution in Visual Studio and restore the Nuget Packages. 
* If you need a username and password to connect to your DB, edit the `Web.Config` file and fill in the `GraphDBUser` and `GraphDBPassword` values in the `appSettings` section.
* Press F5 to run the project, this will start your browser of choice and show you the interface.

=== Run Remotely
* Create a database on http://www.graphenedb.com/[GrapheneDB] or http://www.graphstory.com/[GraphStory] 
* Once created, you need to get the connection details and fill in the `GraphDBUrl`, `GraphDBUser` and `GraphDBPassword` values in the `appSettings` section of the `Web.Release.Config` file.
* Right Click on Neo4jDotNetDemo and Click publish. If you already have an Azure account sign in and follow the steps. If not, you can Sign up today (you can host 10 Free Websites in each region). Alternatively - you can host in any other .NET capable hosting.
